#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const {
  activeSportsFor,
  mergeFeedEvents,
  normalizeFeed,
  readJson,
  summarizeFeedHorizon,
  validateFeed,
  writeJson,
} = require("./lib/feed-utils");

const args = process.argv.slice(2).filter(arg => arg !== "--replace");
const replaceExisting = process.argv.includes("--replace");
const inputPath = args[0] || "feeds/incoming/events.json";
const eventsOutPath = args[1] || "data/events.json";
const metaOutPath = args[2] || "data/feed-meta.json";
const bundleOutPath = args[3] || "data/events.js";

const feed = normalizeFeed(readJson(inputPath));
const errors = validateFeed(feed);

if (errors.length) {
  console.error(`Refusing to publish invalid feed from ${inputPath}:`);
  errors.forEach(error => console.error(`- ${error}`));
  process.exit(1);
}

let publishedFeed = feed;
let mergeSummary = null;
if (!replaceExisting) {
  try {
    const existing = normalizeFeed(readJson(eventsOutPath));
    const existingErrors = validateFeed(existing);
    if (existingErrors.length) {
      throw new Error(existingErrors.join("; "));
    }
    mergeSummary = mergeFeedEvents(feed.events, existing.events);
    publishedFeed = { ...feed, events: mergeSummary.events };
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
}

const publishedErrors = validateFeed(publishedFeed);
if (publishedErrors.length) {
  console.error("Refusing to publish an invalid merged feed:");
  publishedErrors.forEach(error => console.error(`- ${error}`));
  process.exit(1);
}

let meta = {
  version: "unpublished",
  schemaVersion: "events.v1",
  publishedAt: new Date().toISOString(),
  eventsPath: "/data/events.json",
  activeSports: [],
  briefingWeekKey: "manual",
  usesBundledEvents: false,
};

try {
  meta = readJson(metaOutPath);
} catch (error) {
  if (error.code !== "ENOENT") throw error;
}
const nextMeta = {
  ...meta,
  version: publishedFeed.version,
  schemaVersion: publishedFeed.schemaVersion,
  publishedAt: publishedFeed.publishedAt,
  eventsPath: "/" + path.relative(process.cwd(), eventsOutPath).replace(/\\/g, "/"),
  activeSports: activeSportsFor(publishedFeed),
  feedHorizon: summarizeFeedHorizon(publishedFeed),
  usesBundledEvents: false,
};

writeJson(eventsOutPath, publishedFeed);
writeJson(metaOutPath, nextMeta);
fs.mkdirSync(path.dirname(bundleOutPath), { recursive: true });
fs.writeFileSync(
  bundleOutPath,
  `/* Generated by scripts/publish-feed.js. Do not edit directly. */\nglobalThis.NOTHINGSPORTS_EVENTS = ${JSON.stringify(publishedFeed.events, null, 2)};\n`
);

console.log(`Published ${publishedFeed.events.length} events from ${inputPath}`);
if (mergeSummary) console.log(`Preservation merge: ${mergeSummary.preserved} retained, ${mergeSummary.overridden} superseded, ${mergeSummary.added} added.`);
console.log(`Updated ${eventsOutPath}`);
console.log(`Updated ${metaOutPath}`);
console.log(`Updated ${bundleOutPath}`);
console.log(`Feed version: ${feed.version}`);
